### ISSUE TITLE
[Suggestion] Migrate to Protocol Buffers

### ISSUE THREAD

**Issue by X1nto** [Roadcrosser/JSON-G#3]
Hi! I'm really fascinated by this project. The fact that technology has come so far that we can store a whole image in JSON amazes me! However, we all know that JSON is not the fastest data-exchanging format. So, I was thinking, what if you guys used [Protocol Buffers](https://developers.google.com/protocol-buffers) instead? I personally think it would let you guys develop the most useless image store, alongside the most inefficient one. I'm pretty sure people would LOVE to use Protobuf instead of JSON.

I really hope you take a look at this suggestion for the sake of humanity and its future. 

Sincerely, DN.

**Comment by Roadcrosser** [comment]
Unfortunately I'm not well-versed enough in protobuf to be able to add an integration. You are free to PR such a thing, however I feel that this may be better suited as a separate project.

I'm currently attending Sawcon so I'll have to get back to you on that one.

**Comment by X1nto** [comment]
Thanks for responding, I will take a look and PR the Protobuf migration whenever I'm free. However, due to the start of a Bofa season, it might take some time for me to start working on it.

**Comment by ItzOnlyAnimal** [comment]
> I'm currently attending Sawcon so I'll have to get back to you on that one.
What's Sawcon? And where does it take place?
